{"additions": 12, "auther_ref": "CorrectExceptionMessage", "auther_sha": "0c13d81de333644405160deca4807e6c4b2dc548", "author": "wmtan", "body": "There is an existing exception message designed for the case where the reuse of a process name results in a duplicate product of the same type with the same input tag.\nUnfortunately, the same exception is thrown when the duplication is a result of the same product being registered more than once in the current process. In this second case, the exception message is not only misleading, but flat out wrong.\nThis PR distinguishes the two cases, and adds a new exception to be thrown in the second case.\nThis PR solves issue #13268 \n", "branch": "CMSSW_8_1_X", "changed_files": 1, "closed_at": "1456302978", "comments": 11, "commits": 1, "created_at": "1456169330", "deletions": 3, "labels": ["comparison-available", "core-approved", "fully-signed", "orp-pending", "tests-approved"], "merge_commit_sha": "181f246195e050667a59c45e36dc49b17d1cc389", "merged_at": "1456302978", "merged_by": "davidlange6", "milestone": "Next CMSSW_8_1_X", "number": 13432, "release-notes": [], "review_comments": 1, "state": "closed", "title": "Fix incorrect exception message", "updated_at": "1458163153", "user": "wmtan"}