{"additions": 2, "auther_ref": "patch-4", "auther_sha": "adc5459a7fcf453afefc2d6a01d03a8d03a428b4", "author": "makortel", "body": "#### PR description:\r\n\r\nThis should fix the failures seen in CMSSW_12_0_PY3_X_2021-05-23-2300\r\n\r\n#### PR validation:\r\n\r\nNone", "branch": "master", "changed_files": 1, "closed_at": "1622008830", "comments": 19, "commits": 1, "created_at": "1621853695", "deletions": 1, "labels": ["code-checks-approved", "fully-signed", "l1-approved", "orp-approved", "tests-approved", "upgrade-approved"], "merge_commit_sha": "6714a87c1ce8160a0ec9dec58b7c5a183044c0b0", "merged_at": "1622008830", "merged_by": "cmsbuild", "milestone": "CMSSW_12_0_X", "number": 33822, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Fix import in Phase1L1TJetSumsProducer_cfi for python 3", "updated_at": "1622008830", "user": "makortel"}