{"additions": 16, "auther_ref": "IB/CMSSW_9_2_X/gcc530-revert-fs", "auther_sha": "792a1db06977671bde4a1ad29df5086ce8403ea1", "author": "gudrutis", "body": "Problem:\r\n'xrootdpyfs' depends on 'fs' versions (>=0.4.0,<2.0), it was not listed as dependency.\r\n\r\nResolution:\r\n'fs' reverted to version 0.5.5a1, listed as 'xrootdpyfs' dependency.", "branch": "IB/CMSSW_9_2_X/gcc530", "changed_files": 5, "closed_at": "1506578971", "comments": 13, "commits": 2, "created_at": "1506433514", "deletions": 20, "labels": ["externals-approved", "fully-signed", "orp-pending", "tests-approved"], "merge_commit_sha": "0b9e0847c0649ffa0d755c0dc68d083d0d8ef9f7", "merged_at": "1506578971", "merged_by": "smuzaffar", "number": 3454, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Backported xrootdpyfs fix from 9_4_X", "updated_at": "1506578971", "user": "gudrutis"}