{"additions": 34, "auther_ref": "exception_when_no_sources", "auther_sha": "a012aaf9a27aaf416c4a2e1e4e1f5409ca2c760d", "author": "bbockelm", "body": "If a read call was performed after XrdFile threw an exception, it\nis possible there are no active sources.  However, not all paths\ncheck for the case of zero sources and may use-after-free the last\nsource.\n\nThis caused a deadlock at the Tier-0.\n\n@davidlange6 @Dr15Jones @slava77 \n", "branch": "CMSSW_7_5_5_patchX", "changed_files": 1, "closed_at": "1448829670", "comments": 3, "commits": 1, "created_at": "1448826814", "deletions": 1, "labels": ["comparison-pending", "core-pending", "pending-signatures", "tests-pending"], "merge_commit_sha": "0672254d002e882a3ddd5ef1894c95009ab3f08e", "merged_at": "1448829670", "merged_by": "cmsbuild", "milestone": "Next CMSSW_7_5_5_patchX", "number": 12590, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Fail read calls after exception.", "updated_at": "1448829670", "user": "bbockelm"}