{"additions": 1, "auther_ref": "fix-ut-phytools", "auther_sha": "1ad2c77bdb86b5c3b105b2a74711abff494a71b3", "author": "mrodozov", "body": "#### PR description:\r\n\r\nFixes unit test \r\nhttps://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc820/CMSSW_11_2_PY3_X_2020-08-27-2300/PhysicsTools/PythonAnalysis\r\n\r\n#### PR validation:\r\n\r\nThe test run for both python2 and 3 in normal IB and PY3 IB\r\n", "branch": "master", "changed_files": 1, "closed_at": "1598683770", "comments": 11, "commits": 1, "created_at": "1598600176", "deletions": 1, "labels": ["analysis-approved", "code-checks-approved", "comparison-available", "fully-signed", "orp-approved", "tests-approved"], "merge_commit_sha": "d9773dae26c8c7b283baa885e33a7c6eff30797b", "merged_at": "1598683770", "merged_by": "cmsbuild", "milestone": "CMSSW_11_2_X", "number": 31275, "release-notes": [], "review_comments": 0, "state": "closed", "title": "[PY3] Fix unit test in PhysicsTools/PythonAnalysis", "updated_at": "1598683770", "user": "mrodozov"}