{"additions": 34, "auther_ref": "CMSSW_7_6_1/test12590-a012aaf-reb", "auther_sha": "63675bc6af9e0083c2cd1f9c50bede95241f23d8", "author": "slava77", "body": "If a read call was performed after XrdFile threw an exception, it\nis possible there are no active sources.  However, not all paths\ncheck for the case of zero sources and may use-after-free the last\nsource.\n\nThis caused a deadlock at the Tier-0.\n", "branch": "CMSSW_7_6_X", "changed_files": 1, "closed_at": "1448896989", "comments": 10, "commits": 1, "created_at": "1448852154", "deletions": 1, "labels": ["comparison-available", "core-approved", "fully-signed", "orp-pending", "tests-approved"], "merge_commit_sha": "491b80017811dee1ffc6c08b5df0223f9d8f1230", "merged_at": "1448896989", "merged_by": "cmsbuild", "milestone": "CMSSW_7_6_X", "number": 12593, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Fail read calls after exception. (same as #12590)", "updated_at": "1448899461", "user": "slava77"}