{"additions": 17, "auther_ref": "protect_taskHasFailed", "auther_sha": "58e901e546103cb6d304914c10f9aefd368f54eb", "author": "Dr15Jones", "body": "#### PR description:\r\n\r\nWaitingTask*Holder::taskHasFailed could call exceptionPtr() while the underlying object is being set. This change makes calls to exceptionPtr() safe across threads.\r\n\r\nThanks to @wddgit for catching this case.\r\n\r\n#### PR validation:\r\n\r\nCode compiles and FWCore/Concurrency unit tests pass.", "branch": "master", "changed_files": 3, "closed_at": "1658155283", "comments": 11, "commits": 2, "created_at": "1657915076", "deletions": 8, "labels": ["core-approved", "fully-signed", "tests-approved", "orp-approved", "code-checks-approved"], "merge_commit_sha": "88f3ad0637578007e073ab791cd349ae4922bc48", "merged_at": "1658155283", "merged_by": "cmsbuild", "milestone": "CMSSW_12_5_X", "number": 38765, "release-notes": [], "review_comments": 5, "state": "closed", "title": "Protect WaitingTask*Holder::taskHasFailed from a data race", "updated_at": "1658155283", "user": "Dr15Jones"}