{"additions": 17, "auther_ref": "protect_taskHasFailed", "auther_sha": "58e901e546103cb6d304914c10f9aefd368f54eb", "author": "Dr15Jones", "body": "#### PR description:\r\n\r\nWaitingTask*Holder::taskHasFailed could call exceptionPtr() while the underlying object is being set. This change makes calls to exceptionPtr() safe across threads.\r\n\r\nThanks to @wddgit for catching this case.\r\n\r\n#### PR validation:\r\n\r\nCode compiles and FWCore/Concurrency unit tests pass.", "branch": "master", "changed_files": 3, "comments": 8, "commits": 2, "created_at": "1657915076", "deletions": 8, "labels": ["core-pending", "pending-signatures", "tests-approved", "orp-pending", "code-checks-approved"], "milestone": "CMSSW_12_5_X", "number": 38765, "release-notes": [], "review_comments": 3, "state": "open", "title": "Protect WaitingTask*Holder::taskHasFailed from a data race", "updated_at": "1658019097", "user": "Dr15Jones"}