{"additions": 318, "auther_ref": "updated_MTDTrackQualityMVA_BDT", "auther_sha": "509d009841c1b816d96df018d3476bc0d172b544", "author": "MartinKlevs", "body": "#### PR description:\r\n\r\nUpdated the MTDTrackQualityMVA code with a new and improved BDT model. The new BDT has a few extra input parameters and was trained on a dataset with updated pT cuts. The BDT part of `MVATrainingNtuple.cc` has been rewritten to be more similar to `Validation/MtdValidation/plugins/MtdTracksValidation.cc` and to output a few additional track parameters. The training and performance of the BDT is described in this [presentation](https://indico.cern.ch/event/1565764/#4-status-of-the-track-mtd-matc).\r\n\r\nThe updated BDT code uses a new [model file](https://github.com/cms-data/RecoMTD-TimingIDTools/pull/2) that is is expected to be located at `RecoMTD/TimingIDTools/data`.\r\n\r\n#### PR validation:\r\n\r\nThis code has been tested using\r\n`runTheMatrix.py -l limited -i all --ibeos`\r\n\r\nThere were no errors from the MTDTrackQualityMVA module, however some of the analysis workflows couldn't access some of the required root files. I'm not sure if that is an issue because it is caused by unavailable datasets and not the code itself. The file read errors contained `[3011] No servers are available to read the file`.\r\n\r\nThe BDT was also tested using the `29834.0_TTbar_14TeV+Run4D110PU` workflow where everything worked as expected.", "branch": "master", "changed_files": 4, "comments": 5, "commits": 1, "created_at": "1752059251", "deletions": 223, "labels": ["reconstruction-pending", "pending-signatures", "tests-approved", "orp-pending", "upgrade-pending", "requires-external", "code-checks-approved"], "milestone": "CMSSW_15_1_X", "number": 48514, "release-notes": [], "review_comments": 0, "state": "open", "title": " MTD reconstruction: updated MTD track quality BDT", "updated_at": "1752070143", "user": "MartinKlevs"}