{"additions": 11, "auther_ref": "pythonTools3", "auther_sha": "160e6c5577f2f74f4a211c197cd2f9202729e067", "author": "davidlange6", "body": "I modified pythia8-toolfile by mistake. This reverts that change", "branch": "IB/CMSSW_10_2_X/gcc630next", "changed_files": 1, "closed_at": "1523284250", "comments": 1, "commits": 1, "created_at": "1523284242", "deletions": 8, "labels": ["externals-pending", "orp-pending", "pending-signatures", "tests-pending"], "merge_commit_sha": "cd98997cd9aa45273b628c334ab444edbe9f3381", "merged_at": "1523284250", "merged_by": "davidlange6", "number": 3907, "release-notes": [], "review_comments": 0, "state": "closed", "title": "One more tool file fix", "updated_at": "1523284260", "user": "davidlange6"}